"""Claude Code adapter: renders CLAUDE.md, .claude/rules, .claude/skills, and .claude/agents.

Every file points into docs/engineering/; no engineering knowledge is duplicated here.
"""

from __future__ import annotations

from pathlib import Path
from string import Template

from bootstrap.compose import GENERATOR, GENERATOR_VERSION, Composition, OutputFile

NAME = "claude"
TEMPLATES = Path(__file__).parent / "templates"
NOTE = f"Generated by {GENERATOR} {GENERATOR_VERSION}. Owned by this project: edit freely."


def _template(name: str) -> Template:
    return Template((TEMPLATES / name).read_text(encoding="utf-8"))


def _yaml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(comp: Composition) -> list[OutputFile]:
    standards = "\n".join(f"- {d.title}: `{d.path}`" for d in comp.core_docs)
    profile_lines = []
    for p in comp.profiles:
        profile_lines.append(f"- **{p.name}** (`{p.doc.path}`)")
        profile_lines += [f"  - {line}" for line in p.summary]
    skills = "\n".join(f"- `/{w.id}` - {w.description}" for w in comp.workflows)

    files = [
        OutputFile(
            "CLAUDE.md",
            _template("CLAUDE.md.tmpl").substitute(
                generated_note=NOTE,
                project_name=comp.project_name,
                operating_contract="\n".join(f"- {line}" for line in comp.core_summary),
                standards=standards,
                profiles="\n".join(profile_lines),
                skills=skills,
            ),
        )
    ]

    rule = _template("rule.md.tmpl")
    for p in comp.profiles:
        if not p.applies_to:
            # No file scope: the profile is reachable from CLAUDE.md and the skills instead.
            continue
        files.append(
            OutputFile(
                f".claude/rules/{p.name}.md",
                rule.substitute(
                    paths="\n".join(f"  - {_yaml_str(g)}" for g in p.applies_to),
                    generated_note=NOTE,
                    title=p.doc.title,
                    doc_path=p.doc.path,
                ),
            )
        )

    skill = _template("skill.md.tmpl")
    for w in comp.workflows:
        files.append(
            OutputFile(
                f".claude/skills/{w.id}/SKILL.md",
                skill.substitute(
                    name=w.id,
                    description=_yaml_str(w.description),
                    generated_note=NOTE,
                    title=w.id.replace("-", " ").title(),
                    doc_path=w.path,
                ),
            )
        )

    files.append(
        OutputFile(
            ".claude/agents/code-reviewer.md",
            _template("agents/code-reviewer.md").substitute(
                generated_note=NOTE,
                standards="\n".join(f"   - `{d.path}`" for d in comp.core_docs),
                profiles="\n".join(f"   - `{p.doc.path}`" for p in comp.profiles) or "   - (none)",
            ),
        )
    )
    return files
