"""Render the tool-neutral knowledge tree (docs/engineering/) shared by every adapter.

The output depends only on the Composition, never on which tools were selected.
"""

from __future__ import annotations

from bootstrap.compose import DOCS_ROOT, GENERATOR, GENERATOR_VERSION, PROJECT_DOC, Composition, OutputFile

HEADER = (
    f"<!-- Generated by {GENERATOR} {GENERATOR_VERSION}. Owned by this project: edit freely. "
    "Re-running the generator never overwrites edited files. -->\n\n"
)


def _rel(path: str) -> str:
    return path.removeprefix(DOCS_ROOT + "/")


def _index(comp: Composition) -> str:
    lines = [
        "# Engineering Knowledge Base",
        "",
        "The single, tool-neutral source of engineering standards for this project.",
        "Coding-agent instruction files only point here; switching agents does not change this directory.",
        "",
        "- [Project](PROJECT.md) - architecture, commands, and project-specific decisions",
        "",
        "## Standards and governance",
        "",
    ]
    lines += [f"- [{d.title}]({_rel(d.path)})" for d in comp.core_docs]
    lines += ["", "## Active profiles", ""]
    lines += [f"- [{p.doc.title}]({_rel(p.doc.path)}) (`{p.id}` {p.version}) - {p.description}" for p in comp.profiles]
    lines += ["", "## Workflows", ""]
    lines += [f"- [{w.id}]({_rel(w.path)}) - {w.description}" for w in comp.workflows]
    return HEADER + "\n".join(lines) + "\n"


def _project_seed(comp: Composition) -> str:
    return HEADER + f"""# {comp.project_name}

Project-specific context shared by every coding agent and every developer.
Fill in the TODOs once; agent instruction files load or link this file.

## Overview

TODO: What this project does, for whom, and its current status.

## Architecture

TODO: Main components, how they interact, and where each lives in the repository.

## Commands

TODO: Exact commands to install, run, test, lint, and type-check.

| Task | Command |
|------|---------|
| Install | TODO |
| Test | TODO |
| Lint | TODO |
| Run locally | TODO |

## Directory map

TODO: Top-level directories and what belongs in each.

## Technology decisions

TODO: Providers, frameworks, data stores, and model choices, with the reason for each.

## Project-specific rules

TODO: Constraints that override or extend docs/engineering standards for this project.
"""


def render(comp: Composition) -> list[OutputFile]:
    files = [
        OutputFile(f"{DOCS_ROOT}/README.md", _index(comp)),
        OutputFile(PROJECT_DOC, _project_seed(comp), seed_only=True),
    ]
    for doc in comp.core_docs:
        files.append(OutputFile(doc.path, HEADER + doc.source.read_text(encoding="utf-8")))
    for profile in comp.profiles:
        files.append(OutputFile(profile.doc.path, HEADER + profile.doc.source.read_text(encoding="utf-8")))
    for wf in comp.workflows:
        files.append(OutputFile(wf.path, HEADER + wf.source.read_text(encoding="utf-8")))
    return files
