"""Codex adapter: renders a concise root AGENTS.md that maps into docs/engineering/.

Nested AGENTS.md files and .agent/PLANS.md are intentionally not generated in v0.1:
the neutral implementation workflow already carries the execution-plan guidance.
"""

from __future__ import annotations

from pathlib import Path
from string import Template

from bootstrap.compose import GENERATOR, GENERATOR_VERSION, Composition, OutputFile

NAME = "codex"
TEMPLATES = Path(__file__).parent / "templates"
NOTE = f"Generated by {GENERATOR} {GENERATOR_VERSION}. Owned by this project: edit freely."


def render(comp: Composition) -> list[OutputFile]:
    profile_lines = []
    for p in comp.profiles:
        scope = f" Applies to: {', '.join(f'`{g}`' for g in p.applies_to)}." if p.applies_to else ""
        profile_lines.append(f"- **{p.name}**: `{p.doc.path}`.{scope}")
        profile_lines += [f"  - {line}" for line in p.summary]

    content = Template((TEMPLATES / "AGENTS.md.tmpl").read_text(encoding="utf-8")).substitute(
        generated_note=NOTE,
        project_name=comp.project_name,
        operating_contract="\n".join(f"- {line}" for line in comp.core_summary),
        standards="\n".join(f"- {d.title}: `{d.path}`" for d in comp.core_docs),
        profiles="\n".join(profile_lines),
        workflows="\n".join(f"- **{w.id}** (`{w.path}`): {w.description}" for w in comp.workflows),
    )
    return [OutputFile("AGENTS.md", content)]
